# Generated by Django 3.0 on 2019-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOfficeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('approval_status', models.CharField(choices=[('pending', 'Request pending'), ('approved', 'Request approved'), ('declined', 'Request declined')], max_length=100, verbose_name='Approval Status')),
            ],
        ),
    ]
