# Generated by Django 3.0 on 2019-12-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0002_auto_20191214_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktime',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
