# Generated by Django 3.0 on 2019-12-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0003_auto_20191214_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktime',
            old_name='timestamp',
            new_name='timestamp1',
        ),
    ]
