# Generated by Django 3.0 on 2019-12-14 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0004_auto_20191214_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checktime',
            name='timestamp1',
        ),
        migrations.AddField(
            model_name='checktime',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
