# Generated by Django 3.0 on 2019-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0005_auto_20191214_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktime',
            name='in_or_out',
            field=models.CharField(choices=[('in', 'checkin'), ('out', 'checkout')], max_length=20, verbose_name='Check in or out'),
        ),
        migrations.AlterField(
            model_name='checktime',
            name='name_text',
            field=models.CharField(blank='False', default='', max_length=200, verbose_name='Name'),
        ),
    ]
