# Generated by Django 3.0 on 2019-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0006_auto_20191214_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktime',
            name='name_text',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
    ]
